// apps/angular/src/app/app.component.ts
import { Component, inject } from '@angular/core';
import { NgIf } from '@angular/common';

import {FormBuilder, Validators, ReactiveFormsModule, FormGroup} from '@angular/forms';

import { validateIBAN } from "ngx-iban-validator";

@Component({
  selector: 'app-root',
  imports: [NgIf,ReactiveFormsModule],
  templateUrl: './app.component.html',
  styleUrl: './app.component.css'
})
export class AppComponent {
  title = 'angular';
  formBuilder = inject(FormBuilder);
  ibanForm = this.formBuilder.group({
    iban: [null, [Validators.required, validateIBAN]],
  });
  submit(form: FormGroup) {
    const { valid, value } = form;
    const { iban } = value;
    if (valid) {
      alert(`IBAN: ${iban}, is valid!`);
    }
  }
}

<div class="page">
  <form [formGroup]="ibanForm" (ngSubmit)="submit(ibanForm)">
    <h2>NGX IBAN Validator</h2>
    <div>
      <input
        type="text"
        formControlName="iban"
        placeholder="Enter IBAN"
        autocomplete="off"
      />
      <button [disabled]="ibanForm.invalid">Submit</button>
    </div>
    <div class="validation-errors">
      <small
        *ngIf="
                ibanForm.get('iban')?.errors && ibanForm.get('iban')?.errors?.['ibanInvalid']
              "
      >
        <span
          *ngIf="ibanForm.get('iban')?.errors?.['error']['countryUnsupported']"
        >
          Country not supported
        </span>
        <span
          *ngIf="ibanForm.get('iban')?.errors?.['error']['codeLengthInvalid']"
        >
          IBAN Code length is invalid
        </span>
        <span *ngIf="ibanForm.get('iban')?.errors?.['error']['patternInvalid']">
          IBAN Code pattern is invalid
        </span>
      </small>
    </div>
  </form>
</div>

// apps/vue/src/App.vue
<script setup lang="ts">
import { ref } from 'vue';
import { validateIBAN } from 'ngx-iban-validator';

const iban = ref('');
const validationResult = ref<any>(null);

function validate() {
  const control = iban.value;
  validationResult.value = validateIBAN(control);
}

function alertResult() {
  alert(`IBAN: ${iban.value}, is valid!`);
}
</script>

<template>
  <div class="page">
    <form @submit.prevent="alertResult">
      <h2>NGX IBAN Validator</h2>
      <div>
        <input
          v-model="iban"
          type="text"
          placeholder="Enter IBAN"
          autocomplete="off"
          @input="() => validate()"
        />
        <button :disabled="!validationResult || validationResult?.ibanInvalid">
          Submit
        </button>
      </div>
      <div class="validation-errors">
        <small v-if="validationResult?.error && validationResult?.ibanInvalid">
          <span v-if="validationResult?.error?.countryUnsupported">
            Country not supported
          </span>
          <span v-if="validationResult?.error?.codeLengthInvalid">
            IBAN Code length is invalid
          </span>
          <span v-if="validationResult?.error?.patternInvalid">
            IBAN Code pattern is invalid
          </span>
        </small>
      </div>
    </form>
  </div>
</template>

<style scoped>
.page {
  height: 100vh;
  display: flex;
  justify-content: center;
  align-items: center;
}
h2 {
  text-align: center;
}
form {
  padding: 20px;
}
input {
  padding: 10px;
}
button {
  padding: 10px;
}
.validation-errors {
  color: red;
}
</style>
